### ISSUE TITLE
crash while installing app on android 12

### ISSUE THREAD

**Issue by UltraBlackLinux** [kitsunyan/foxy-droid#109]
Hey there,
I was wondering if Android 12 support was official already.
When I try to install anything I get this error: 
```
FATAL EXCEPTION: main
Process: com.looker.droidify, PID: 30323
java.lang.IllegalArgumentException: com.looker.droidify: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
	at android.app.PendingIntent.buildServicePendingIntent(PendingIntent.java:724)
	at android.app.PendingIntent.getService(PendingIntent.java:686)
	at com.looker.droidify.service.DownloadService$stateNotificationBuilder$2.invoke(DownloadService.kt:374)
	at com.looker.droidify.service.DownloadService$stateNotificationBuilder$2.invoke(DownloadService.kt:365)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.looker.droidify.service.DownloadService.getStateNotificationBuilder(DownloadService.kt:365)
	at com.looker.droidify.service.DownloadService.handleDownload(DownloadService.kt:421)
	at com.looker.droidify.service.DownloadService.access$handleDownload(DownloadService.kt:34)
	at com.looker.droidify.service.DownloadService$Binder.enqueue(DownloadService.kt:125)
	at com.looker.droidify.utility.Utils.startUpdate(Utils.kt:151)
	at com.looker.droidify.screen.ProductFragment.onActionClick(ProductFragment.kt:389)
	at com.looker.droidify.screen.ProductAdapter.onCreateViewHolder$lambda-29$lambda-28(ProductAdapter.kt:984)
	at com.looker.droidify.screen.ProductAdapter.$r8$lambda$AVjhZsz2gt2d1EQ7MdGzS6z-yis(Unknown Source:0)
	at com.looker.droidify.screen.ProductAdapter$$ExternalSyntheticLambda2.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7455)
	at android.view.View.performClickInternal(View.java:7432)
	at android.view.View.access$3700(View.java:835)
	at android.view.View$PerformClick.run(View.java:28810)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```
Can you do anything about this
Thanks!

**Comment by triallax** [comment]
You seem to be using [Droid-ify](https://github.com/Iamlooker/Droid-ify), not Foxy Droid.

**Comment by UltraBlackLinux** [comment]
Ah yes. Thanks. I seem to have mindlessly clicked the first link that somewhat resembled a source.
