### ISSUE TITLE
Foxy droid crashs

### ISSUE THREAD

**Issue by Qyrln** [kitsunyan/foxy-droid#34]
Hello , Dev
Foxy droid crashes when I open f-droid links 
V:1.2
`FATAL EXCEPTION: main
Process: nya.kitsunyan.foxydroid, PID: 23819
java.lang.RuntimeException: Unable to start activity ComponentInfo{nya.kitsunyan.foxydroid/nya.kitsunyan.foxydroid.MainActivity}: kotlin.KotlinNullPointerException
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2699)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2766)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1507)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:153)
	at android.app.ActivityThread.main(ActivityThread.java:6244)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
Caused by: kotlin.KotlinNullPointerException
	at nya.kitsunyan.foxydroid.screen.TabsFragment.onSaveInstanceState(TabsFragment.kt:316)
	at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:2864)
	at androidx.fragment.app.FragmentStateManager.saveBasicState(FragmentStateManager.java:434)
	at androidx.fragment.app.FragmentStateManager.saveInstanceState(FragmentStateManager.java:425)
	at androidx.fragment.app.FragmentManager.saveFragmentInstanceState(FragmentManager.java:985)
	at nya.kitsunyan.foxydroid.screen.ScreenActivity.pushFragment(ScreenActivity.kt:133)
	at nya.kitsunyan.foxydroid.screen.ScreenActivity.handleIntent(ScreenActivity.kt:225)
	at nya.kitsunyan.foxydroid.MainActivity.handleIntent(MainActivity.kt:18)
	at nya.kitsunyan.foxydroid.screen.ScreenActivity.onCreate(ScreenActivity.kt:95)
	at android.app.Activity.performCreate(Activity.java:6684)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2652)
	... 9 more`

**Comment by kitsunyan** [comment]
Should be fixed in https://github.com/kitsunyan/foxy-droid/commit/bee6af56caeb845de8fdd4884ebf51b2242d8af6
