### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by fabianski7** [kitsunyan/foxy-droid#6]
when trying to open the application this is the error that android captures

```
time: 1592830902095
msg: java.lang.IllegalStateException: versionName must not be null
stacktrace: java.lang.RuntimeException: Unable to create application nya.kitsunyan.foxydroid.MainApplication: java.lang.IllegalStateException: versionName must not be null
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6465)
	at android.app.ActivityThread.access$1300(ActivityThread.java:219)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:915)
Caused by: java.lang.IllegalStateException: versionName must not be null
	at nya.kitsunyan.foxydroid.MainApplication.toInstalledItem(MainApplication.kt:34)
	at nya.kitsunyan.foxydroid.MainApplication.listenApplications(MainApplication.kt:105)
	at nya.kitsunyan.foxydroid.MainApplication.onCreate(MainApplication.kt:48)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1190)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
	... 8 more
```

OnePlus 6
Havoc 3.5 - Android 10
Kernel 4.9.225

**Comment by kitsunyan** [comment]
https://github.com/kitsunyan/foxy-droid/issues/2

**Comment by fabianski7** [comment]
Why did you close the other issue if it still exists? I didn't see any other open, so I created this one.

**Comment by kitsunyan** [comment]
But I didn't, the author of issue closed it.

> I didn't see any other open, so I created this one.

That's how it works, issues often get closed when they're resolved, not when fix released. It's a good practice to look at closed issues as well.
